### PR TITLE
Fixed 'ArrayIndexOutOfBoundsException: 2' for all 2-arguments methods

### PR DESCRIPTION
**Pull request by vbachurin**
Fix for #7

### CODE REVIEW

**Comment by facaiy** [comment]
Many thanks, Vlad. I'll release 0.0.3 at weekend :-)

**Comment by vbachurin** [comment]
@facaiy please release :)

**Comment by facaiy** [comment]
@vbachurin 0.0.2 has been released, thank you, Vlad

**Comment by vbachurin** [comment]
Great! Thanks Yan.

**Comment by facaiy** [comment]
You're welcome. But I can't find 0.2.0 in https://mvnrepository.com/artifact/io.github.facaiy/math-expression-parser, perhaps it stills need a little time for synchronization. Feel free to ping me if needed :-)

**Pull request merged**
